### ISSUE TITLE
《深入了解const》一文中的笔误

### ISSUE THREAD

**Issue by wzhe** [JiaweiHawk/jiaweihawk.github.io#4]
感谢作者的文章，让我掌握了函数指针/指针数组相关的内容。
> 找到`*`，即char (*(*x())[])();，因此函数的返回值为char类型
  左边遇到完结，结束

这里应该是
> 找到`char`

[深入了解const 原文链接](https:jiaweihawk.gitee.io/2021/07/15/%E6%B7%B1%E5%85%A5%E4%BA%86%E8%A7%A3const/)

**Comment by JiaweiHawk** [comment]
感谢你的纠正:)！
这里应该更改为你纠正的那样，我会在空闲的时候修复这里。
